on:
  pull_request:
  push:
    branches: [ 'master' ]

name: build

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        env:
          update: true
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC'
          coverage: xdebug

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run tests with PHPUnit
        run: vendor/bin/phpunit --colors=always --coverage-clover=coverage.xml

      - name: Upload coverage to Coveralls
        if: matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@v2
        with:
          file: ./coverage.xml
